### ISSUE TITLE
Error: No device detected. Is it plugged in?

### ISSUE THREAD

**Issue by johannesgensheimer** [IntelRealSense/meta-intel-realsense#18]
Hello,

I get this error when running rs-enumerate-devices: "No device detected. Is it plugged in?"
When I run, for example, rs-depth I get: "No device detected. Is it plugged in?"

Details about the system:
Realsense camera: Realsense Depth Camera D435
Board: Jetson TX2 development board
Branch: Rocko

When I run lsusb and lsusb -t I get:
root@(none):/usr# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 8086:0b07 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@(none):/usr# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci-tegra/3p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci-tegra/4p, 480M
    |__ Port 1: Dev 2, If 0, Class=Video, Driver=, 480M
    |__ Port 1: Dev 2, If 1, Class=Video, Driver=, 480M
    |__ Port 1: Dev 2, If 2, Class=Video, Driver=, 480M
    |__ Port 1: Dev 2, If 3, Class=Video, Driver=, 480M
    |__ Port 1: Dev 2, If 4, Class=Video, Driver=, 480M

So the Camera is recogniced by the Board, but not by the library.
Does anyone know this issue?

Best,

Johannes

**Comment by srware** [comment]
If the Jetson BSP has it's own kernel you will need to create the required patches for it [see here](https://github.com/IntelRealSense/meta-intel-realsense/tree/master/recipes-kernel/linux) . We only provide patches for stock Poky and Intel kernels in this layer.

**Comment by johannesgensheimer** [comment]
So should it be enough to just rename the kernel-yocto recipes?
Do you know if the rocko branch is even compatible with a D435 camera?

**Comment by srware** [comment]
The rocko branch has recipes for v2.10.4 of librealsense which had support for D435 camera although it is an old release so there will have been bugfixes and enhancements since.

Renaming the kernel recipes will likely not be enough. You might be lucky if the Jetson BSP uses one of the kernel versions with patches already provided but if it uses a different kernel version you will need to create patches from scratch.
