### ISSUE TITLE
Add uvcvideo.ko to install modules list

### ISSUE THREAD

**Issue by elPrac** [IntelRealSense/meta-intel-realsense#21]
Hi!

I was getting problems with pyrealsense2 in my builds because the following error showed up
```
"No device connected"
````
I just needed to add uvcvideo to:
```
MACHINE_EXTRA_RDEPENDS = "kernel-module-uvcvideo"
```
But generally this variable is set in a machine.conf and for me it was difficult to append or overwrite this variable so maybe it will be nice to have this on a **RRECOMMENDS=** variable I don't know what you think or perhaps there is a better way i already test his with an append recipe and using [meta-tegra](https://github.com/madisongh/meta-tegra) with a jetson-nano, if someone find this useful i can make a patch or something...
i'm not a Yocto expert so please let me know your comments.

BR,

**Comment by scooter1556** [comment]
Hi @elPrac,

For the standard Yocto kernel "linux-yocto" and Intel kernel "linux-intel" this is handled by this layer appending the kernel config: [See Here](https://github.com/IntelRealSense/meta-intel-realsense/blob/master/recipes-kernel/linux/linux-yocto/uvc.cfg).

This might not be the cleanest way to do it these days however there are also kernel patches required for some RealSense cameras which don't have upstream kernel support which also won't be applied to the 'linux-tegra' kernel built by "meta-tegra".

From a maintenance perspective it's impossible to add patches to this layer for all of the hardware support layers out there however it generally isn't too difficult to take the patches and uvc.cfg used for the "linux-yocto" kernel and adapt them. You might find simply renaming the "linux-yocto_4.19.bbappend" file to "linux-tegra_4.19.bbappend" is enough.

Thanks.

**Comment by srware** [comment]
Hi @elPrac,

For the standard Yocto kernel "linux-yocto" and Intel kernel "linux-intel" this is handled by this layer appending the kernel config: [See Here](https://github.com/IntelRealSense/meta-intel-realsense/blob/master/recipes-kernel/linux/linux-yocto/uvc.cfg).

This might not be the cleanest way to do it these days however there are also kernel patches required for some RealSense cameras which don't have upstream kernel support which also won't be applied to the 'linux-tegra' kernel built by "meta-tegra".

From a maintenance perspective it's impossible to add patches to this layer for all of the hardware support layers out there however it generally isn't too difficult to take the patches and uvc.cfg used for the "linux-yocto" kernel and adapt them. You might find simply renaming the "linux-yocto_4.19.bbappend" file to "linux-tegra_4.19.bbappend" is enough.

Thanks.
