### ISSUE TITLE
realsense usb device No search

### ISSUE THREAD

**Issue by carlo0120** [IntelRealSense/meta-intel-realsense#22]
branch zeus-draft
machine jetson nano

bitbake core-image-sato

ex) cd /dev/HID-SENSOR-2000e1.4.auto
usb device No search

USB Input dmesg Log 
[88035.933707] usb 2-1.1: new SuperSpeed Gen 1 USB device number 8 using tegra-xusb
[88035.954262] usb 2-1.1: New USB device found, idVendor=8086, idProduct=0b3a
[88035.954263] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[88035.954264] usb 2-1.1: Product: Intel(R) RealSense(TM) Depth Camera 435i
[88035.954264] usb 2-1.1: Manufacturer: Intel(R) RealSense(TM) Depth Camera 435i
[88035.954265] usb 2-1.1: SerialNumber: xxxxxxxxxxx

**Comment by srware** [comment]
@carlo0120 , what kernel is being built as part of your build?

If there it isn't one of the ones with patches provided by [this layer](https://github.com/IntelRealSense/meta-intel-realsense/tree/master/recipes-kernel/linux) then you will need to create your own patches and append the relevant kernel recipe to get full support for the camera.

**Comment by carlo0120** [comment]
recipes-kernel/linux/linux-tegra_4.9.bb

https://github.com/madisongh/meta-tegra/tree/master/recipes-kernel/linux

**Comment by srware** [comment]
@carlo0120 , thanks. There are no patches in this layer for "linux-tegra". I maintain patches for the default Yocto kernels and Intel kernels but the maintenance task becomes too great extending support to other platforms.

You may find that simply renaming existing "linux-yocto_4.9.bbappend" to "linux-tegra_4.9.bbappend" will work but as the patches haven't been created against this specific kernel source tree there are no guarantees.

**Comment by carlo0120** [comment]
I did a kernel patch but
uvcvideo doesn't seem to be active.
uvcvideo operation log is missing.
Do you know how?

**Comment by srware** [comment]
Have you also included the necessary uvc.cfg when building the kernel? See [https://github.com/IntelRealSense/meta-intel-realsense/blob/master/recipes-kernel/linux/linux-yocto/uvc.cfg](https://github.com/IntelRealSense/meta-intel-realsense/blob/master/recipes-kernel/linux/linux-yocto/uvc.cfg)

**Comment by carlo0120** [comment]
ucv.cfg Patched

I included print in the code, but it doesn't print.
uvc_driver.c
uvc_init()
{
...
printk("uvc_init\n");
...
}
uvc_video.c
uvc_video_enable()
{
...
printk("uvc_video_enable\n");
...
}

**Comment by carlo0120** [comment]
kernel menuconfig Modify
Problem solved
close
