### ISSUE TITLE
can't connect to the camera

### ISSUE THREAD

**Issue by ChipHunter** [IntelRealSense/meta-intel-realsense#29]
Hi All,

I am facing an issue when trying to use the "Intel(R) RealSense(TM) Depth Camera 435i" with Nvidia Jetson Xavier nx and yocto. I am trying to run the example application and getting the following error :
`root@jetson-xavier-nx-devkit:~# rs-hello-realsense
RealSense error calling rs2_pipeline_start(pipe:0x556501e980):
    No device connected`

I can see that librealsense is installed on the system: 

`root@jetson-xavier-nx-devkit:~# find / -name "*realsense*" 
/usr/lib/librealsense2.so.2.39
/usr/lib/librealsense2.so.2.39.0
/usr/lib/librealsense2-gl.so.2.39
/usr/lib/librealsense2-gl.so.2.39.0
/usr/bin/rs-hello-realsense`

and the kernel logs show that the camera is detected 

`Dec 16 17:25:17 jetson-xavier-nx-devkit kernel: usb 2-3.3: New USB device found, idVendor=8086, idProduct=0b3a
Dec 16 17:25:17 jetson-xavier-nx-devkit kernel: usb 2-3.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 16 17:25:17 jetson-xavier-nx-devkit kernel: usb 2-3.3: Product: Intel(R) RealSense(TM) Depth Camera 435i
Dec 16 17:25:17 jetson-xavier-nx-devkit kernel: usb 2-3.3: Manufacturer: Intel(R) RealSense(TM) Depth Camera 435i
`
also 

`root@jetson-xavier-nx-devkit:~# cat /sys/bus/usb/devices/*/product
USB Keyboard
4-Port USB 2.0 Hub
Bluetooth Radio
Intel(R) RealSense(TM) Depth Camera 435i
4-Port USB 3.0 Hub
xHCI Host Controller
xHCI Host Controller`

But still the application can't find the camera. I'd appreciate your support. 

Thanks in advance

**Comment by srware** [comment]
Hi @ChipHunter  

Can you confirm what kernel you are running and what BSP layer the image was built with. There are patches in this layer for the "linux-tegra" 4.9 kernel but for most of the patches we assume the "meta-tegra" layer has been used which includes the RealSense patches.

You can try the Userspace driver to determine if this is a kernel issue by adding the following to your build config:
`
PACKAGECONFIG_pn-librealsense2 = "rsusb"
`

**Comment by ChipHunter** [comment]
Thank you very much for the nice and quick reply!

After adding the suggested configuration I can see that the camera is identified

`root@jetson-xavier-nx-devkit:~# rs-hello-realsense 

The camera is facing^Cn object 3.439 meters away 
`
The poky image is generated with meta-tegra layer and I am building the core-image-minimal 

`root@jetson-xavier-nx-devkit:~# uname -ar

Linux jetson-xavier-nx-devkit 4.9.140-l4t-r32.4+ga28ca7b3779d #1 SMP PREEMPT Thu Jan 28 11:30:48 UTC 2021 aarch64 GNU/Linux`

What do you think am I missing here?

**Comment by ChipHunter** [comment]
An update:

I removed the build directory and built again. I noticed the following warning. Is that something relevant to the issue at hand? 

ARNING: linux-tegra-4.9.140+gitAUTOINC+a28ca7b377-r0 do_kernel_configcheck: [kernel config]: specified values did not make it into the kernel's final configuration:

    [NOTE]: 'CONFIG_VIDEO_V4L2' last val (m) and .config val (y) do not match
    [INFO]: CONFIG_VIDEO_V4L2 : y ## .config: 3476 :configs//./uvc.cfg (m) 
    [INFO]: raw config text:

        config VIDEO_V4L2
                tristate
                default (I2C || I2C = n) && VIDEO_DEV
                depends on (I2C || I2C = n) && VIDEO_DEV

        Config 'VIDEO_V4L2' has the following Direct dependencies (VIDEO_V4L2=n):
                n
        Parent dependencies are:
             I2C [y] VIDEO_DEV [n]
    [INFO]: config 'CONFIG_VIDEO_V4L2' was set, but it wasn't assignable, check (parent) dependencies
    [NOTE]: 'CONFIG_VIDEOBUF2_CORE' last val (m) and .config val (y) do not match
    [INFO]: CONFIG_VIDEOBUF2_CORE : y ## .config: 3482 :configs//./uvc.cfg (m) 
    [INFO]: raw config text:

        config VIDEOBUF2_CORE
                tristate
                select DMA_SHARED_BUFFER

        Config 'VIDEOBUF2_CORE' has the following Direct dependencies (VIDEOBUF2_CORE=n):
                n
        Parent dependencies are:
             DMA_SHARED_BUFFER [n]
    [INFO]: config 'CONFIG_VIDEOBUF2_CORE' was set, but it wasn't assignable, check (parent) dependencies
    [NOTE]: 'CONFIG_VIDEOBUF2_MEMOPS' last val (m) and .config val (y) do not match
    [INFO]: CONFIG_VIDEOBUF2_MEMOPS : y ## .config: 3483 :configs//./uvc.cfg (m) 
    [INFO]: raw config text:

        config VIDEOBUF2_MEMOPS
                tristate
                select FRAME_VECTOR

        Config 'VIDEOBUF2_MEMOPS' has the following Direct dependencies (VIDEOBUF2_MEMOPS=n):
                n
        Parent dependencies are:
             FRAME_VECTOR [n]
    [INFO]: config 'CONFIG_VIDEOBUF2_MEMOPS' was set, but it wasn't assignable, check (parent) dependencies
    [NOTE]: 'CONFIG_VIDEOBUF2_VMALLOC' last val (m) and .config val (y) do not match
    [INFO]: CONFIG_VIDEOBUF2_VMALLOC : y ## .config: 3485 :configs//./uvc.cfg (m) 
    [INFO]: raw config text:

        config VIDEOBUF2_VMALLOC
                tristate
                select VIDEOBUF2_CORE
                select VIDEOBUF2_MEMOPS
                select DMA_SHARED_BUFFER

        Config 'VIDEOBUF2_VMALLOC' has the following Direct dependencies (VIDEOBUF2_VMALLOC=n):
                n
        Parent dependencies are:
             VIDEOBUF2_CORE [n] DMA_SHARED_BUFFER [n] VIDEOBUF2_MEMOPS [n]
    [INFO]: config 'CONFIG_VIDEOBUF2_VMALLOC' was set, but it wasn't assignable, check (parent) dependencies
    [NOTE]: 'CONFIG_IIO_TRIGGERED_BUFFER' last val (m) and .config val (y) do not match
    [INFO]: CONFIG_IIO_TRIGGERED_BUFFER : y ## .config: 5306 :configs//./hid.cfg (m) 
    [INFO]: raw config text:

        config IIO_TRIGGERED_BUFFER
                tristate
                select IIO_TRIGGER
                select IIO_KFIFO_BUF
                help
                  Provides helper functions for setting up triggered buffers.

        Config 'IIO_TRIGGERED_BUFFER' has the following Direct dependencies (IIO_TRIGGERED_BUFFER=n):
                n
        Parent dependencies are:
             IIO_KFIFO_BUF [y] IIO_TRIGGER [y]
    [INFO]: config 'CONFIG_IIO_TRIGGERED_BUFFER' was set, but it wasn't assignable, check (parent) dependencies

**Comment by srware** [comment]
@ChipHunter 

Good catch, it does look like the kernel configs have been updated and are now conflicting. I have tried removing any config overrides from this layer in "master" branch. I will test tomorrow to see if this resolves those issues and if any kernel config is missing as a result. It's likely that V4L is simply being fully or partially disabled in the kernel build causing the problem.

**Comment by ChipHunter** [comment]
Hi @srware 

I applied the changes you did and updated the meta-tegra to the latest. But I can still see the problem? Am I still missing something? I'd be very grateful if you'd share the results of your test with me. 

Thanks!

**Comment by scooter1556** [comment]
Hi @ChipHunter 

I have explored this a bit more this morning and it does seem that all of the required kernel modules are being patched and compiled so I can only assume that the uvcvideo kernel module isn't being installed in the default image for your platform. I have updated the "master" branch with the required config for the linux-tegra kernel as a precaution and also added the uvcvideo kernel module as a recommended package for librealsense2 which should ensure it makes it into the final image.

You can also try adding the following to your local.conf:

`
MACHINE_EXTRA_RRECOMMENDS_append_jetson-xavier-nx-devkit = " kernel-module-uvcvideo"
`

**Comment by srware** [comment]
@ChipHunter 

All looks good on the USB side. Annoyingly my only Nvidia platform (Jetson Nano) is failing to boot... so testing this is proving difficult. I will take a look at the kernel source and make sure all of the code patches are present.

**Comment by scooter1556** [comment]
@ChipHunter 

I have just updated "master" branch with an updated set of patches for the tegra kernel. I can't say I saw anything missing related to the D435i though so i'm not convinced this is the issue.

A couple of other things to try:

Firmware update of the camera: https://dev.intelrealsense.com/docs/firmware-update-tool

Given the D435i includes the HID devices it might be worth making sure these kernel modules are included in your build in case this is blocking the camera initializing correctly:

kernel-module-hid-sensor-accel-3d
kernel-module-hid-sensor-gyro-3d
kernel-module-hid-sensor-iio-common
kernel-module-hid-sensor-trigger

**Comment by ChipHunter** [comment]
Hi @scooter1556 and @srware, 

After adding the kernel modules, the camera was discovered and it worked correctly. 

I'd like to thank you very much for the great support!

**Comment by srware** [comment]
@ChipHunter 

Many thanks for confirming you got it working. That's great news!
