### ISSUE TITLE
realsense-objectrecognition breaks build with latest Yocto master branch

### ISSUE THREAD

**Issue by sakoman** [IntelRealSense/meta-intel-realsense#3]
The realsense-objectrecognition recipe seems to be trying to populate sysroot with libunwind.so.8.

Is this intentional?

ERROR: libunwind-1.1+gitAUTOINC+bc8698fd7e-r0 do_populate_sysroot_setscene: The recipe libunwind is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
   /mnt/jenkins-ssd/workspace/waipio-2.2-ia64/build/tmp/sysroots/intel-corei7-64/usr/lib/libunwind.so.8
 Matched in b'manifest-intel-corei7-64-realsense-objectrecognition.populate_sysroot'
Please verify which recipe should provide the above files.
The build has stopped as continuing in this scenario WILL break things, if not now, possibly in the future (we've seen builds fail several months later). If the system knew how to recover from this automatically it would however there are several different scenarios which can result in this and we don't know which one this is. It may be you have switched providers of something like virtual/kernel (e.g. from linux-yocto to linux-yocto-dev), in that case you need to execute the clean task for both recipes and it will resolve this error. It may be you changed DISTRO_FEATURES from systemd to udev or vice versa. Cleaning those recipes should again resolve this error however switching DISTRO_FEATURES on an existing build directory is not supported, you should really clean out tmp and rebuild (reusing sstate should be safe). It could be the overlapping files detected are harmless in which case adding them to SSTATE_DUPWHITELIST may be the correct solution. It could also be your build is including two different conflicting versions of things (e.g. bluez 4 and bluez 5 and the correct solution for that would be to resolve the conflict. If in doubt, please ask on the mailing list, sharing the error and filelist above.
ERROR: libunwind-1.1+gitAUTOINC+bc8698fd7e-r0 do_populate_sysroot_setscene: If the above message is too much, the simpler version is you're advised to wipe out tmp and rebuild (reusing sstate is fine). That will likely fix things in most (but not all) cases.

**Comment by avishaymahluf** [comment]
Hi @sakoman,

We've removed libunwind from the realsense-objectrecognition recipe.
This issue should't occur again.

Thanks,
Avishay
