### ISSUE TITLE
"No Device Connected" Error with D435i

### ISSUE THREAD

**Issue by jason-dennis11** [IntelRealSense/meta-intel-realsense#30]
Hello, 

I am experiencing a connection issue when using the Intel RealSeense Depth Camera D435i. When attempting to run the example application and I am getting the following error: 
`root@localhost:~# rs-enumerate-devices
No device detected. Is it plugged in?
`

However, when running the same example application with the D415 camera it functions appropriately. With that, I am sure that librealsense is installed on the system and I know the camera is detected (see log below), but for some reason I cannot get the application to run the camera. I saw a similar issue posted (#25) but none of the suggestions there seemed to help.

I would appreciate any other suggestions and support you could offer. 

-------------------------------------

machine: 
`imx8mp6`

uname -a output: 
`Linux 5.4.70`

Camera: 
`Intel Corp. Intel(R) RealSense(TM) Depth Camera 435i`

Branch: 
`hardknott` (added zeus to LAYERSERIES_COMPAT_intel-realsense option)

Dmesg output:
[    3.926406] udevd[272]: starting version 3.2.8
[    3.963966] udevd[272]: invalid key/value pair in file /etc/udev/rules.d/99-librealsense2-libusb.rules on line 79, starting at character 154 ('.')
[    3.982866] udevd[273]: starting eudev-3.2.8
[    4.101718] CAN device driver interface
[    4.111317] uvcvideo: Unknown video format 00000050-0000-0010-8000-00aa00389b71
[    4.134537] uvcvideo: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435i (8086:0b3a)
[    4.145035] uvcvideo 2-1.2:1.0: Entity type for entity Intel(R) RealSense(TM) Depth Ca was not initialized!
[    4.155254] uvcvideo 2-1.2:1.0: Entity type for entity Processing 2 was not initialized!
[    4.163451] uvcvideo 2-1.2:1.0: Entity type for entity Camera 1 was not initialized!
[    4.167734] user_gpios: loading out-of-tree module taints kernel.
[    4.171464] input: Intel(R) RealSense(TM) Depth Ca as /devices/platform/32f10108.usb/38200000.dwc3/xhci-hcd.1.auto/usb2/2-1/2-1.2/2-1.2:1.0/input/input4
[    4.191804] user_gpios user_gpios: no ACPI companion available
[    4.200117] uvcvideo: Unknown video format 36315752-1a66-a242-9065-d01814a8ef8a
[    4.207511] uvcvideo: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435i (8086:0b3a)
[    4.217104] user_gpios user_gpios: no ACPI companion available
[    4.222548] uvcvideo 2-1.2:1.3: Entity type for entity Processing 7 was not initialized!
[    4.231138] uvcvideo 2-1.2:1.3: Entity type for entity Extension 8 was not initialized!
[    4.239223] uvcvideo 2-1.2:1.3: Entity type for entity Camera 6 was not initialized!
[    4.250200] usbcore: registered new interface driver uvcvideo

**Comment by srware** [comment]
Hi @jason-dennis11,

Support for linux-imx kernel was removed last year because meta-freescale maintenance was slow and kept breaking builds so there are no kernel patches available for your platform.

That said, you should still be able to use the libuvc backend (user-space driver) by adding the following to your build config (e.g. local.conf):

`PACKAGECONFIG_pn-librealsense2 = "rsusb"`

It's like the D415 works because support for this camera is in the mainline kernel so no additional patches are required.

**Comment by jason-dennis11** [comment]
Hi @srware, 

Thanks for the quick reply and the clarification. Adding that option to my build config seemed to have worked and I can now run the rs examples.
