### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by juanmcc** [IntelRealSense/meta-intel-realsense#33]
Hi, I'm trying to add this layer to yocto hardknott project for imx8-mp board (Hummingboard Mate).  But there is some problems with repositories and librealsense2.inc file.

I receive this error:

> ERROR: librealsense2-2.44.0-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export PATH="/home/ubuntu/yocto_hardknott_realsense/sources/poky/scripts:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot-native/usr/sbin:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot-native/usr/bin:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot-native/sbin:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot-native/bin:/home/ubuntu/yocto_hardknott_realsense/sources/poky/bitbake/bin:/home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/hosttools"; export HOME="/home/ubuntu"; git -c core.fsyncobjectfiles=0 ls-remote git://github.com/IntelRealSense/librealsense.git  failed with exit code 128, output:
> fatal: unable to connect to github.com:
> github.com[0: 140.82.121.3]: errno=Connection timed out

But, if I change the repository url from librealsense2.inc for this:

```
SRC_URI = "https://github.com/IntelRealSense/librealsense.git;protocol=https;tag=v${PV}"
SRC_URI[sha256sum] = "2d128b34889d3433c992f20c758d1bd102bb424b33f095ac6eb4167e833724a8"
```

I receive other error, related with "Remove-R200-fix-from-udev-rules.patch": 

```
> ERROR: librealsense2-2.44.0-r0 do_patch: Command Error: 'quilt --quiltrc /home/ubuntu/yocto_hardknott_realsense/build-xwayland-imx8mpsolidrun/tmp/work/cortexa53-crypto-poky-linux/librealsense2/2.44.0-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
> stdout: Applying patch Remove-R200-fix-from-udev-rules.patch
> (Stripping trailing CRs from patch; use --binary to disable.)
> can't find file to patch at input line 15
> Perhaps you used the wrong -p or --strip option?
> The text leading up to this was:
> --------------------------
> |From e3151a52558c6882003d69602c6ebc86ff47c35a Mon Sep 17 00:00:00 2001
> |From: Scott Ware <scott.r.ware@intel.com>
> |Date: Mon, 8 Jun 2020 10:58:12 +0100
> |Subject: [PATCH 2/3] Remove R200 fix from udev rules
> |
> |Signed-off-by: Scott Ware <scott.r.ware@intel.com>
> |---
> | config/99-realsense-libusb.rules | 2 +-
> | 1 file changed, 1 insertion(+), 1 deletion(-)
> |
> |diff --git a/config/99-realsense-libusb.rules b/config/99-realsense-libusb.rules
> |index 0144322..e3eb567 100644
> |--- a/config/99-realsense-libusb.rules
> |+++ b/config/99-realsense-libusb.rules
> --------------------------
> No file to patch.  Skipping patch.
> 1 out of 1 hunk ignored
> Patch Remove-R200-fix-from-udev-rules.patch does not apply (enforce with -f)
> 
> stderr:

```

What is wrong here?

**Comment by srware** [comment]
I assume your build environment is failing with the git protocol but does work with https. It should be sufficient just to add 'protocol=https' to the SRC_URI line:

`SRC_URI = "git://github.com/IntelRealSense/librealsense.git;protocol=https;tag=v${PV}"`

I will push the changes to the hardknott branch although bear in mind hardknott is now end of life so support will be limited.

**Comment by juanmcc** [comment]
Thank you so much, it works fine for me. I know hardknott is now end of life, but for my project I can't use newer versions.
