### ISSUE TITLE
Realsens 435i: " device has no listeners, quitting"

### ISSUE THREAD

**Issue by juanmcc** [IntelRealSense/meta-intel-realsense#34]
Hi, I have built a Hardknott Yocto system with Realsense layer included on IMX8 Hummingboard Mate. I'm trying my system with Realsense camera, and when I have plugged the Realsense 435i or 455 I have received this message: 

```
[   38.878776] uvcvideo: Unknown video format 36315752-1a66-a242-9065-d01814a8ef8a
[   38.886113] uvcvideo: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435i (8086:0b3a)
[   38.899611] hid-generic 0003:8086:0B3A.0001: device has no listeners, quitting

```

Checking about this error, I have done this:

`bitbake -f -c compile imx-image-full`

Add this line to auto.conf: 

`PACKAGECONFIG_pn-librealsense2 = "rsusb"`

And then rebuild the yocto image:

`bitbake imx-image-full`

What is wrong with this?

EDIT: With Realsense 435 works fine, is this for yocto version? 

Thank you so much.

**Comment by srware** [comment]
Hi @juanmcc ,

The kernel message is expected unless you have a patched kernel with native support for both the V4L side of the camera and in the case of the D435i and D455 also the IMU HID device. This layer doesn't include patches for the IMX kernel. When you build the library with RSUSB enabled it builds a user-space driver for the camera which doesn't depend on native kernel support but there are a few limitations (e.g. single camera only) and stability can be an issue with older libusb versions.

Have you tried loading realsense-viewer or another application which uses librealsense to see if the camera is operational despite the kernel log messages?

**Comment by juanmcc** [comment]
> Hi @juanmcc ,
> 
> The kernel message is expected unless you have a patched kernel with native support for both the V4L side of the camera and in the case of the D435i and D455 also the IMU HID device. This layer doesn't include patches for the IMX kernel. When you build the library with RSUSB enabled it builds a user-space driver for the camera which doesn't depend on native kernel support but there are a few limitations (e.g. single camera only) and stability can be an issue with older libusb versions.
> 
> Have you tried loading realsense-viewer or another application which uses librealsense to see if the camera is operational despite the kernel log messages?

My mistake you are right. The message appears, but rs-depth works fine. Thank you so much @srware
