### ISSUE TITLE
Issue with Intel RealSense Camera Integration on yocto build

### ISSUE THREAD

**Issue by mabasith** [IntelRealSense/meta-intel-realsense#43]
i am having an issue with the integration of the Intel RealSense camera(435i )on the yocto-standard. Below are the details:

Setup Details:

Yocto Image: Created using Poky, 
Kernel Version: Linux v4x 5.10.147-yocto-standard 
Architecture: aarch64 GNU/Linux
recipe used from dunfell branch
Issue Observations:

The camera is visible in the lsusb output with the ID 8086:0B3A, indicating that the hardware is recognized by the USB subsystem.
The kernel correctly detects the camera as a UVC (USB Video Class) device.
However, when launching the camera using the RealSense application, the log "No device connected" is displayed.
how resolve this ?

**Comment by srware** [comment]
Hi @mabasith ,

At this point the dunfell branch is long out of support and builds a version of librealsense which is from 2019.

Looking at the [camera firmware docs](https://dev.intelrealsense.com/docs/firmware-releases-d400) the minimum firmware version for the 435i camera requires at least 2.38.1 but your camera may have an even newer firmware version. I'd recommend moving to a newer supported branch and checking the SDK version supports the FW on your camera.
